[package]
name = "wow_assistant"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "wow_assistant_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4.7"
xcap = { version = "0.9.8", features = ["image"] }
image = { version = "0.25.10", features = ["default"] }
windows-sys = { version = "0.59", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Threading",
    "Win32_Graphics_Gdi",
] }
tract-onnx = "0.23.8"
ort = { version = "2.0.0-rc.13", features = ["directml", "ndarray"] }
ndarray = "0.17"




# 开发模式下对所有第三方依赖（神经网络与图像算法）开启极致优化
# 既保证开发调试增量编译极快，又让 tract-onnx 纯 CPU 深度学习推理提速 100+ 倍！
[profile.dev.package."*"]
opt-level = 3

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

